config/routes.rb
Rails.application.routes.draw do

  resources :discussions do 
    resources :comments
  end

  resources :projects do
     resources :discussions
  end

  devise_for :users

  root "projects#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :discussion
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	has_many :comments
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :discussions
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :projects
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @discussion=Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.create!(comment_params)
    @comment.save
    redirect_to @discussion
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :discussion_id)
    end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @discussions = Discussion.all
    respond_with(@discussions)
  end

  def show
    respond_with(@discussion)
  end

  def new
    @discussion = Discussion.new
    respond_with(@discussion)
  end

  def edit
  end

  def create
    @project=Project.find(params[:project_id])
    @discussion = @project.discussions.create!(discussion_params)
    @discussion.save
    respond_with(@discussion)
  end

  def update
    @discussion.update(discussion_params)
    respond_with(@discussion)
  end

  def destroy
    @discussion.destroy
    respond_with(@discussion)
  end

  private
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    def discussion_params
      params.require(:discussion).permit(:title, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :discussion_id %><br>
    <%= f.number_field :discussion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Discussion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.discussion_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Discussion:</strong>
  <%= @comment.discussion_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/discussions/_form.html.erb
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.collection_select :project_id, Project.all, :id, :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.title %></td>
        <td><%= discussion.project_id %></td>
        <td><%= link_to 'Show', discussion %></td>
        <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @discussion.title %>
</p>

<p>
  <strong>Project:</strong>
  <%= @discussion.project.title %>
</p>

<h3>Comments</h3>
<% @discussion.comments.each do |c| %>
<%= c.content %><br>
<% end %>
<div class="container">
<h3>New Comment</h3>
<%= form_for([@discussion,Comment.new]) do |f| %>
<div class="field">
<%= f.label :content %><br>
<%= f.text_area :content, :class=>"form-control" %>
</div>
<%= f.submit "Add Comment", :class => "btn btn-primary" %>
</div>
<% end %>

<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', project_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basecamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="alert"><p id="notice"><%= notice %></p></div>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>User:</strong>
  <%= current_user.email.to_s %>
</p>
<% if @project.discussions.size != 0 %>
<br><br>these are the discussions under this project : <br><br>

<% @project.discussions.each do |c| %>
<%=link_to c.title , discussion_path%><br>
<% end %><br>
<% end %>
<%= form_for([@project,Discussion.new]) do |f| %>
<div class="field">
	Create Discussion <br>
<%= f.label :Title %><br>
<%= f.text_field :title, :class=>"form-control" %>
</div>
<%= f.submit "Create", :class => "btn btn-primary" %>
</div>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>